### ISSUE TITLE
Getting IndexError while running the script

### ISSUE THREAD

**Issue by catvasily** [marcomusy/pianoplayer#32]
Hello. 
I installed pianoplayer in Windows 7 and Anaconda with --no-devs option.
Was able to start pianoplayer:
> python C:\ProgramData\Anaconda3\Scripts\pianoplayer
In "Import Score" I selected a .mid file (a relatively simple song with 2 channels).
While running, I got an error message:
...
meas.None   finger:5 on C5      v=0.1      [5, 4, 3, 4, 2] d:5
meas.None   finger:4 on B4      v=0.1      [4, 3, 4, 2, 2] d:5
meas.None   finger:3 on A4
meas.None   finger:4 on B4
meas.None   finger:2 on G4
meas.None   finger:3 on G4
meas.None   finger:3 on G4
meas.None   finger:2 on D4
meas.None   finger:4 on E4
meas.None   finger:1 on G3
meas.None   finger:0 on G4
Your hand span set to size-M which is 17.22 cm
(max relaxed distance between thumb and pinkie)
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\ProgramData\Anaconda3\Scripts\pianoplayer", line 89, in generateCMD
    self.lh.noteseq = reader(sf, beam=self.LeftHandBeam)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pianoplayer\scorereader.py",
line 32, in reader
    strm = sf.parts[beam].flat
File "C:\ProgramData\Anaconda3\lib\site-packages\music21\stream\iterator.py",
line 325, in __getitem__ 
    e = fe[k]
IndexError: list index out of range

Any suggestion? Would be happy to send you the .mid file, if it helps.
Thank you for developing this toolbox!

**Comment by marcomusy** [comment]
Hi Vasily - yes that would be helpful otherwise I have no way to reproduce the issue,
Thanks!
Marco

**Comment by catvasily** [comment]
Thank you, Marco, for a quick reply!
Here it is.
[We_Three_Kings.zip](https://github.com/marcomusy/pianoplayer/files/5826494/We_Three_Kings.zip)

**Comment by marcomusy** [comment]
That's a strange error! there must be something fishy in the midi... I will check.. meanwhile I could export it in musescore and then it works ok:

[We_Three_Kings.pdf](https://github.com/marcomusy/pianoplayer/files/5826511/We_Three_Kings.pdf)

[We_Three_Kings.zip](https://github.com/marcomusy/pianoplayer/files/5826513/We_Three_Kings.zip)

**Comment by catvasily** [comment]
Thanks, Marco! 
Possibly.
Although I was able to play this midi file in Synthesia and Piano From Above without any issues.

**Comment by catvasily** [comment]
Hi again, Marco.
I tried what you suggested:
1) Converted midi to mxl in MuseScore3.
2) Opened the newly created mxl file with your GUI and ran your script.
3)  Output.xml was generated with no errors!
4) Was able to see the finger numbering in output.xml with MuseScore3.
However, when I tried to export output.xml back to midi in MuseScore3, the finger numbering's gone in midi.
I guess this is a limitation of MuseScore. 
So, if we can do finger numbering directly from midi into midi with your script, it would be great!.
Or, regardless of the input format, the output will be in xml format?
Thank you and regards.

**Comment by marcomusy** [comment]
Are you sure that midi supports lyrics? After a quick search it looks it doesn't:
https://www.midi.org/forum/4852-what-about-midi-2-0-and-lyrics-in-midi-files

The pianoplayer output is only music-xml, I think musescore has a command-line converter which might make life easier.

**Comment by catvasily** [comment]
Hi Marco,
Does your question assume that the numbers indicating fingers are actually stored as lyrics?
I thought there would a specific field in the XML and midi format just for finger hints.

**Comment by marcomusy** [comment]
Hi, no they are by default stored in the fingering slot of xml-music format.
Optionally `pianoplayer` can store them as lyrics, but only from command line with -b option, e.g.
`pianoplayer -b somefile.mscz`

**Comment by Cool-Joe** [comment]
Midi can store texts like lyrics, e.g. "FF 05 len text Lyric" and other texts.
See http://www.music.mcgill.ca/~ich/classes/mumt306/StandardMIDIfileformat.html
However the used music32 lib does not support it. It would be a good idea to implement this feature in music21.

**Comment by marcomusy** [comment]
last error should be fixed in the latest release.
