### ISSUE TITLE
Cannot visualize: `ERROR: texture file wood1 does not exist`

### ISSUE THREAD

**Issue by toku-sa-n** [marcomusy/pianoplayer#46]
Hello. I'm trying to visualize my MIDI file with this command:

```sh
pianoplayer midi_file.midi -vz
```

However, the command fails with these errors:
```
[vedo.mesh.py:463] ERROR: texture file wood1 does not exist
[vedo.mesh.py:463] ERROR: texture file wood1 does not exist
Traceback (most recent call last):
  File "/home/hiroki/.local/bin/pianoplayer", line 224, in <module>
    vk = VirtualKeyboard(songname=xmlfn)
  File "/home/hiroki/.local/lib/python3.9/site-packages/pianoplayer/vkeyboard.py", line 41, in __init__
    self.build_keyboard()
  File "/home/hiroki/.local/lib/python3.9/site-packages/pianoplayer/vkeyboard.py", line 91, in build_keyboard
    self.vp += Text('PianoPlayer ^'+__version__+" ",
NameError: name 'Text' is not defined
```

I couldn't find the texture files on my computer. How can I get them?

**Comment by marcomusy** [comment]
Hi thanks for reporting
my guess is that you have a incompatible `vedo` version, try:
```
pip install vedo==2020.4.2 -U
```

**Comment by toku-sa-n** [comment]
Thank you, that command solved the problem.
By the way, I've installed `pianoplayer` with `pip install --user pianoplayer`. I don't understand python fully, but since the [`requirements.txt`](https://github.com/marcomusy/pianoplayer/blob/master/requirements.txt) contains `vedo==2020.4.2`, I think vedo should have been installed at that time. Did I miss something?
