### ISSUE TITLE
I got trouble with this particular score

### ISSUE THREAD

**Issue by mhoangvslev** [marcomusy/pianoplayer#5]
```
Traceback (most recent call last):
  File "/usr/local/bin/pianoplayer", line 155, in <module>
    rh.generateFingering(nmeasures=Nmeasures)
  File "/usr/local/lib/python2.7/dist-packages/pianoplayer/hand.py", line 221, in generateFingering
    bestfpos = self.set_fingers_positions(out, ninenotes, i)
  File "/usr/local/lib/python2.7/dist-packages/pianoplayer/hand.py", line 83, in set_fingers_positions
    newfpos[j]= self.fpos[j] + ni.x - ifx
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```
Sample file: https://musescore.com/user/5506406/scores/2084736

**Comment by marcomusy** [comment]
in version 1.1.0 aI added a protection if() clause, but the score file seem corrupted in some way
