### ISSUE TITLE
local variable 'ninenotes' referenced before assignment

### ISSUE THREAD

**Issue by Kobe972** [marcomusy/pianoplayer#52]
I installed pianoplayer on windows 11 and imported a simple midi file. When click generate, the command line reports
```
Your hand span set to size-M which is 17.22 cm
(max relaxed distance between thumb and pinkie)
Reading beam 0 with 14 objects in stream.
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\Scripts\pianoplayer", line 83, in generateCMD
    self.rh.generate(nmeasures=self.meas.get())
  File "D:\Users\myhac\AppData\Local\Programs\Python\Python310\lib\site-packages\pianoplayer\hand.py", line 207, in generate
    self.set_fingers_positions(out, ninenotes, 0)
UnboundLocalError: local variable 'ninenotes' referenced before assignment
```

**Comment by pmatos** [comment]
I got the same issue here. Such an interesting project. Shame that this is still happening and has not been fixed yet.

Linux user here, used attached midi file and the following command line:
```
pianoplayer -o scientist-annotated.xml -v -M scientist-coldplay.midi
```
[scientist-coldplay.midi.gz](https://github.com/marcomusy/pianoplayer/files/11781434/scientist-coldplay.midi.gz)

**Comment by pmatos** [comment]
@marcomusy Are you still interested in fixing this? ^

**Comment by pmatos** [comment]
I think this might have been fixed post release, so using git HEAD of master might work.

**Comment by pmatos** [comment]
Unfortunately even in git HEAD of master, `ninenotes` is undefined in `generate`, if we take the `            if i > N - 10:` branch.

**Comment by marcomusy** [comment]
Hi I just uploaded a patch in `pip`:
```
pip install pianoplayer -U
```
Caveat:
the minimum nr of notes to process must be 9 (in the lower beam you had 8), and for chords the output is not very good anyway (but fingering chords has never been a problem..).  

[scientist-coldplay.mscz.gz](https://github.com/marcomusy/pianoplayer/files/11789808/scientist-coldplay.mscz.gz)
